# Generated by Django 4.2.3 on 2023-07-05 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_user_date_joined_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 22, 53, 29, 191951)),
        ),
    ]
