# Generated by Django 4.2.3 on 2023-07-14 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0005_book_average_rating_rating_book_rated_by'),
        ('Users', '0012_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rated_books',
            field=models.ManyToManyField(related_name='books_rated', through='SocialMedia.Rating', to='SocialMedia.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 22, 27, 44, 828645)),
        ),
    ]
