# Generated by Django 4.2.3 on 2023-07-14 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_alter_user_date_joined_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 3, 8, 55, 332872)),
        ),
    ]
