# Generated by Django 4.2.3 on 2023-07-20 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_user_followers_num_user_following_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 2, 47, 47, 509596)),
        ),
    ]
