# Generated by Django 4.2.3 on 2023-07-21 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0017_alter_book_favorited_by_alter_comment_created_at'),
        ('Users', '0033_alter_user_date_joined_alter_user_favorite_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 16, 18, 13, 872701)),
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_books',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(related_name='books_favorited_by', related_query_name='user', through='SocialMedia.FavoriteBook', to='SocialMedia.book'),
        ),
    ]
