# Generated by Django 4.2.3 on 2023-07-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0002_alter_book_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
