# Generated by Django 4.2.3 on 2023-07-21 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0011_remove_author_full_name_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 3, 51, 59, 553082)),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
