# Generated by Django 4.2.3 on 2023-07-21 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0014_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books_written',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 4, 41, 13, 942477)),
        ),
        migrations.AddField(
            model_name='author',
            name='books_written',
            field=models.ManyToManyField(related_name='authors', to='SocialMedia.book'),
        ),
    ]
