# Generated by Django 4.2.3 on 2023-07-21 12:48

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialMedia', '0016_alter_comment_created_at_favoritebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='book',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorited_by_users', related_query_name='book',
                                         through='SocialMedia.FavoriteBook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 16, 18, 13, 881939)),
        ),
    ]
