# Generated by Django 4.2.3 on 2023-07-21 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0018_remove_book_favorited_by_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 16, 20, 4, 750912)),
        ),
        migrations.DeleteModel(
            name='FavoriteBook',
        ),
    ]
