# Generated by Django 4.2.3 on 2023-07-21 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0022_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorited_by',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 16, 33, 25, 623162)),
        ),
    ]
