# Generated by Django 4.2.3 on 2023-07-21 19:36

import SocialMedia.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0024_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=SocialMedia.models.author_image_directory_path),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 23, 6, 4, 143435)),
        ),
    ]
