version: "3.8"

services:
  django_app:
    build:
      context: .
    restart: always
    container_name: chapterone_app
    ports:
      - 127.0.0.1:8002:8000
    volumes:
      - type: bind
        source: ./static
        target: /projects/mehrad/back/ChapterOne/static
      - type: bind
        source: ./media
        target: /projects/mehrad/back/ChapterOne/media
    depends_on:
      - db

  db:
    image: mysql
    container_name: "chapterone_db"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ChapterOne_DB
    volumes:
      - /mehdb/mysql/db:/var/lib/mysql
